Training the TuckER model...
Background knowledge=True
Model= FB15k-237
Number of training data points: 272115
Starting training...
Traceback (most recent call last):
  File "main.py", line 227, in <module>
    experiment.train_and_eval()
  File "main.py", line 147, in train_and_eval
    loss = model.loss(predictions, targets)
  File "c:\users\joss1\.conda\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "c:\users\joss1\.conda\envs\torch\lib\site-packages\torch\nn\modules\loss.py", line 498, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "c:\users\joss1\.conda\envs\torch\lib\site-packages\torch\nn\functional.py", line 2077, in binary_cross_entropy
    input, target, weight, reduction_enum)
RuntimeError: reduce failed to synchronize: cudaErrorAssert: device-side assert triggered
